<div class="option">
	<input class="path" id="destination" disabled="disabled" value="<?= $this->destination ?>" />
	<a href="#" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="serverFileDialog('#destination', $('#destination').val())">
		<span class="ui-button-text">Choose Destination Directory</span>
	</a>
</div>
<div class="option">
	<input class="path" id="source" disabled="disabled" value="<?= $this->source ?>" />
	<a href="#" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="serverFileDialog('#source', $('#source').val())">
		<span class="ui-button-text">Choose Source Directory</span>
	</a>
</div>
<div class="option">
	<a href="#" class="ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" onclick="generateLibrary()">
		<span class="ui-button-text">Generate Library</span>
	</a>
</div>
