<html>
	<head>
<?= $this->headLink()
	->appendStylesheet(PUBLIC_PATH.'/css/ui-lightness/jquery-ui-1.8rc2.custom.css')
	->appendStylesheet(PUBLIC_PATH.'/css/style.css')
	?>
<?= $this->headScript()
	->appendScript('PUBLIC_PATH = "'.PUBLIC_PATH.'";')
	->appendFile(PUBLIC_PATH.'/js/jquery-1.4.2.min.js')
	->appendFile(PUBLIC_PATH.'/js/jquery-ui-1.8rc2.custom.min.js')
	->appendFile(PUBLIC_PATH.'/js/script.js')
	?>
	</head>
	<body>
<?= $this->layout()->content ?>
		<div id="serverFileDialog">
			<input type="hidden" id="serverFileDialogTarget" />
			<div id="path">Loading...</div>
			<div id="files"></div>
		</div>
		<div id="createDirectoryDialog">
			<div>Type a directory name:</div>
			<input id="createDirectoryName" />
			<div class="ui-state-error ui-corner-all" id="createDirectoryDialogError"></div>
		</div>
		<div id="generateStatusDialog">
			<div>Generating library...</div>
			<div class="console" id="generateStatusDialogConsole"></div>
		</div>
	</body>
</html>