<html>
	<head>
<?= $this->jQuery()->uiEnable() ?>
<?= $this->headLink()
	->appendStylesheet(PUBLIC_PATH.'/css/ui-darkness/jquery-ui-1.8rc2.custom.css')
	->appendStylesheet(PUBLIC_PATH.'/css/style.css')
	?>
<?= $this->headScript()
	->appendScript('PUBLIC_PATH = "'.PUBLIC_PATH.'";')
	->appendFile(PUBLIC_PATH.'/js/script.js')
?>
	</head>
	<body>
<?= $this->layout()->content ?>
		<div id="serverFileDialog">
			<div id="path">Loading...</div>
			<div id="actions"><span id="submitServerFileDialog" class="link" target="" onclick="submitServerFileDialog($(this).attr('target'))">Select</span><span class="link" onclick="$('#serverFileDialog').dialog('close');">Cancel</span></div>
			<div id="files"></div>
		</div>
	</body>
</html>